### ISSUE TITLE
Does not work if model already have a boot method

### ISSUE THREAD

**Issue by crissi** [matfish2/eloquent-logger#1]
change traits boot method to bootLogger();

public static function bootLogger()
{

  static::created(function ($model) {
    return $model->logCreated();

  });

  static::updating(function ($model) {
    return $model->logUpdated();
  });

  static::deleting(function ($model) {
    return $model->logDeleted($model);
  });

}

http://www.archybold.com/blog/post/booting-eloquent-model-traits

**Comment by matfish2** [comment]
Thanks! Fixed.
