### ISSUE TITLE
Migration move

### ISSUE THREAD

**Issue by Cannonb4ll** [matfish2/eloquent-logger#2]
Good package, only thing I would like to see different is that you create the migration file, and not let the command run a migration.

This would be better to separate because in development environment you migrate:refresh alot, and this mf_logs table is not getting cleaned with that automatically, so the table always needs to be cleaned manually. (And it would be possible to change the table name as well, sincerely I dont like a table named mf_logs to be honest)

With that said, it would also be cool that you can extend the model Log.php, so we can use our own relations, or add stuff that we want to save to the table aswell. (This would apply to my reply above here, so we can alter migrations ourselfs)

**Comment by ghost** [comment]
+1

**Comment by matfish2** [comment]
Fixed. 
Not sure how to implement your last suggestion regarding the Log model.
You are welcome to send a PR.
