### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by fureszk** [matfish2/eloquent-logger#3]
Breaks the application if I add the package to providers with error:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Illuminate\Foundation\Application::share()
```
Laravel 5.4

**Comment by rettigd** [comment]
I've created a PR to correct this https://github.com/matfish2/eloquent-logger/pull/4

**Comment by ied3vil** [comment]
@matfish2 can you please accept the PR and tag it so we can use it properly?
